name: Build Android Release

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.10.2'


    - name: Decode Release Keystore
      env:
        ENCODED_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
      run: |
        echo $ENCODED_KEYSTORE | base64 --decode > my-upload-key.jks

    - name: Build Release APK and AAB
      env:
        KEYSTORE_PATH: ${{ github.workspace }}/my-upload-key.jks
        STORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
      run: gradle assembleRelease bundleRelease --stacktrace

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: app/build/outputs/apk/release/app-release.apk

    - name: Upload Release AAB
      uses: actions/upload-artifact@v4
      with:
        name: app-release-aab
        path: app/build/outputs/bundle/release/app-release.aab
