name: Build Android Release

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.10.2'


    - name: Create .env file for Ads
      run: |
        echo "ADMOB_APP_ID=ca-app-pub-4989086156410627~4805823860" >> .env
        echo "ADMOB_BANNER_ID=ca-app-pub-4989086156410627/2211450115" >> .env
        echo "ADMOB_INTERSTITIAL_ID=ca-app-pub-4989086156410627/4094955965" >> .env
        echo "ADMOB_APP_OPEN_ID=ca-app-pub-4989086156410627/1105830543" >> .env

    - name: Generate Release Keystore
      run: |
        keytool -genkey -v -keystore my-upload-key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias upload -dname "CN=Gravity Installer, OU=Gravity, O=Gravity, L=Earth, ST=Earth, C=US" -storepass "android" -keypass "android"

    - name: Build Release APK and AAB
      env:
        KEYSTORE_PATH: ${{ github.workspace }}/my-upload-key.jks
        STORE_PASSWORD: android
        KEY_PASSWORD: android
      run: gradle assembleRelease bundleRelease --stacktrace

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: app/build/outputs/apk/release/app-release.apk

    - name: Upload Release AAB
      uses: actions/upload-artifact@v4
      with:
        name: app-release-aab
        path: app/build/outputs/bundle/release/app-release.aab
